apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dxp-service-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "taskruns"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dxp-service-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dxp-service-reader
subjects:
- kind: ServiceAccount
  name: dxp-provisioner
  namespace: dxp-system
- kind: ServiceAccount
  name: default
  namespace: dxp-system
