apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"triggers.tekton.dev/v1beta1","kind":"EventListener","metadata":{"annotations":{},"name":"dxp-demo-listener","namespace":"tekton-pipelines"},"spec":{"serviceAccountName":"tekton-triggers-sa","triggers":[{"bindings":[{"ref":"dxp-demo-binding"}],"name":"dxp-demo-trigger","template":{"ref":"dxp-demo-template"}}]}}
  creationTimestamp: "2026-06-01T15:25:38Z"
  generation: 1
  name: dxp-demo-listener
  namespace: tekton-pipelines
  resourceVersion: "812659"
  uid: b2cacd43-1796-405b-968f-a984f7b56b0c
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: tekton-triggers-sa
  triggers:
  - bindings:
    - kind: TriggerBinding
      ref: dxp-demo-binding
    name: dxp-demo-trigger
    template:
      ref: dxp-demo-template
status:
  address:
    url: http://el-dxp-demo-listener.tekton-pipelines.svc.cluster.local:8080
  conditions:
  - lastTransitionTime: "2026-06-01T15:31:33Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-06-01T15:31:33Z"
    message: Deployment exists
    status: "True"
    type: Deployment
  - lastTransitionTime: "2026-06-01T15:31:33Z"
    message: ReplicaSet "el-dxp-demo-listener-6c8fd98b67" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2026-06-01T15:31:33Z"
    message: EventListener is ready
    status: "True"
    type: Ready
  - lastTransitionTime: "2026-06-01T15:31:33Z"
    message: Service exists
    status: "True"
    type: Service
  configuration:
    generatedName: el-dxp-demo-listener
