apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"el-dxp-demo-nodeport","namespace":"tekton-pipelines"},"spec":{"ports":[{"nodePort":30092,"port":8080,"targetPort":8080}],"selector":{"eventlistener":"dxp-demo-listener"},"type":"NodePort"}}
  creationTimestamp: "2026-06-01T15:39:30Z"
  name: el-dxp-demo-nodeport
  namespace: tekton-pipelines
  resourceVersion: "815711"
  uid: 9a3e01bb-7e62-4e8e-98bc-5c6887c6e521
spec:
  clusterIP: 10.43.140.8
  clusterIPs:
  - 10.43.140.8
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30092
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    eventlistener: dxp-demo-listener
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
