apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: dxp-demo-binding
  namespace: tekton-pipelines
spec:
  params:
  - name: git-url
    value: $(body.repository.clone_url)
  - name: git-revision
    value: $(body.after)
  - name: image
    value: harbor.dxp/dxp/$(body.repository.name)
  - name: app-name
    value: $(body.repository.name)
  - name: namespace
    value: $(body.repository.name)-dev
