apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"triggers.tekton.dev/v1beta1","kind":"TriggerTemplate","metadata":{"annotations":{},"name":"dxp-demo-template","namespace":"tekton-pipelines"},"spec":{"params":[{"name":"git-url"},{"name":"git-revision"},{"name":"image"},{"name":"app-name"},{"name":"namespace"}],"resourcetemplates":[{"apiVersion":"tekton.dev/v1","kind":"PipelineRun","metadata":{"generateName":"dxp-demo-run-","labels":{"backstage.io/kubernetes-id":"$(tt.params.app-name)","dxp.io/managed":"true"},"namespace":"tekton-pipelines"},"spec":{"params":[{"name":"git-url","value":"$(tt.params.git-url)"},{"name":"git-revision","value":"$(tt.params.git-revision)"},{"name":"image","value":"$(tt.params.image)"},{"name":"app-name","value":"$(tt.params.app-name)"},{"name":"namespace","value":"$(tt.params.namespace)"}],"pipelineRef":{"name":"dxp-app-pipeline"},"workspaces":[{"name":"source","volumeClaimTemplate":{"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}}}}}]}}]}}
  creationTimestamp: "2026-06-02T20:52:09Z"
  generation: 4
  name: dxp-demo-template
  namespace: tekton-pipelines
  resourceVersion: "1024067"
  uid: 400e3248-21db-43e8-96ff-96e051ca1678
spec:
  params:
  - name: git-url
  - name: git-revision
  - name: image
  - name: app-name
  - name: namespace
  resourcetemplates:
  - apiVersion: tekton.dev/v1
    kind: PipelineRun
    metadata:
      generateName: $(tt.params.app-name)-run-
      labels:
        backstage.io/kubernetes-id: $(tt.params.app-name)
        dxp.io/managed: "true"
      namespace: tekton-pipelines
    spec:
      params:
      - name: git-url
        value: $(tt.params.git-url)
      - name: git-revision
        value: $(tt.params.git-revision)
      - name: image
        value: $(tt.params.image)
      - name: app-name
        value: $(tt.params.app-name)
      - name: namespace
        value: $(tt.params.namespace)
      pipelineRef:
        name: dxp-app-pipeline
      workspaces:
      - name: source
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
